### ISSUE TITLE
Switch npm ownership to ssbc?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-plugins#7]
cc: @dominictarr 

Just noticed that I can't publish the patch, it's a bit silly that npm always defaults to personal ownership. I know there's `npm owner add $foo` but I *think* that only lets you add other people, not orgs? Sorry to add a chore to your todo list.

**Comment by arj03** [comment]
Yes please, can't publish latest 1.0.3 :)

**Comment by christianbundy** [comment]
I just saw [yesterday](https://github.com/standard/standard/issues/1324#issuecomment-534709834) that you can add modules to an NPM org from the CLI. @dominictarr Could you maybe run that on all SSBC modules? Happy to help however I can.

**Comment by dominictarr** [comment]
@christianbundy done

**Comment by dominictarr** [comment]
I mean on this module...

**Comment by dominictarr** [comment]
for a while I recall that you couldn't have a group as an owner unless it was a scoped module

**Comment by arj03** [comment]
Thank you
